# Generated by Django 3.2.7 on 2021-09-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_reciperequirement_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ManyToManyField(to='inventory.Ingredient'),
        ),
    ]
