# Generated by Django 3.2.7 on 2021-09-27 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210927_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperequirement',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.ingredient'),
        ),
    ]
